### ISSUE TITLE
Type system refactorings for further `rustc_type_ir`-ification

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/wg-traits#124]
# Proposal

I propose the following changes that will have a large footprint, but will ultimately simplify `rustc_type_ir` migration:

1. Get rid of `TypeAndMut` and just have the tykind variant be `RawPtr(Ty, Mutability)`, like how refs are just `Ref(Region, Ty, Mutability)`.

3. Remove the type system's dependency on `hir::Mutability` and `hir::Movability` and copy both of these enums into `rustc_type_ir` (will require converting between `hir::Mutability` and `ty::Mutability` during astconv).

# Mentors or Reviewers

I'll make the changes.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A types team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Types team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/types/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by jackh726** [comment]
Closing as accepted.
