### ISSUE TITLE
April 7: Design meeting for Chalk const support

### ISSUE THREAD

**Issue by jackh726** [rust-lang/wg-traits#15]
This is a meta-issue to basically keep track of when we should have this meeting and that is has/hasn't happened.

**Comment by detrumi** [comment]
[the const generics RFC](https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md)

**Comment by jackh726** [comment]
Conversation link: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/design.20meeting.202020.2E04.2E07/near/193239347

This issue can be closed when the meeting notes get added.

**Comment by nikomatsakis** [comment]
Update:

* had meeting ([zulip logs](https://zulip-archive.rust-lang.org/144729wgtraits/23279designmeeting20200407.html)) and designed a minimal subset
* have a pending PR, [#393](https://github.com/rust-lang/chalk/pull/393)

**Comment by nikomatsakis** [comment]
Update:

* prepreq for landing the PR https://github.com/rust-lang/chalk/issues/452
