### ISSUE TITLE
April 21: Design meeting to discuss implied bounds

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-traits#17]

**Comment by detrumi** [comment]
[mostly up-to-date book chapter on this](https://rustc-dev-guide.rust-lang.org/traits/implied-bounds.html)

**Comment by nikomatsakis** [comment]
We had a good discussion, see [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/design.20meeting.202020.2E04.2E21)
