### ISSUE TITLE
"Chalkify rustc" roadmap planning

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-traits#32]
Discuss the steps and blocking items towards "chalk-ifying" rustc (also define what that *means*)

**Comment by jackh726** [comment]
Scheduled for April 29th. I will prep a doc.

**Comment by nikomatsakis** [comment]
* [Document](https://hackmd.io/vl4nW0bBRReivroArSx6Qw)
* [Zulip meeting log](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/meeting.202022-04-15)
