### ISSUE TITLE
Subtyping and variance chapter review

### ISSUE THREAD

**Issue by jackh726** [rust-lang/wg-traits#37]
Review [#nomicon/340](https://github.com/rust-lang/nomicon/pull/340)

**Comment by jackh726** [comment]
Scheduled for April 8th. Nobody is preparing anything; just going over PR.

**Comment by nikomatsakis** [comment]
Done!

* [Zulip log](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/meeting.202022-04-08)
