### ISSUE TITLE
changes to dropck

### ISSUE THREAD

**Issue by lcnr** [rust-lang/wg-traits#92]
### Summary

discuss dropck in general: its current behavior and the changes in https://github.com/rust-lang/rust/issues/110288 and https://github.com/rust-lang/rfcs/pull/3417 and

### Rationale

the behavior is currently somewhat weird and should be changed. We currently don't have a lot of experts for dropck.

**Comment by BoxyUwU** [comment]
This was [scheduled](https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-07-03.20planning.20meeting/near/372036675) for `17/07/2023`

**Comment by BoxyUwU** [comment]
this meeting was had [here](https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-07-17.20dropck)
